### ISSUE TITLE
Help! Can't get the script to recognize the camera - novice user trying to get RTSP streaming locally

### ISSUE THREAD

**Issue by FS1961** [bmork/defogger#28]
Hello - this could be awesome if I got it working.  I have DCS-8000LH cloud camera which I want to stream local rtsp.

I'm running Ubuntu VM-ware client on a Win10 host. I have verified Wifi and BLE controllers are passed to client..
I don't have a barebones system around. Here is the output from the script:

$ ./dcs8000lh-configure.py b0:c5:54:4c:2d:80 560174
Connecting to b0:c5:54:4c:2d:80...
Traceback (most recent call last):
  File "/home/frank/Downloads/defogger-master/./dcs8000lh-configure.py", line 152, in <module>
    cam = BleCam(args.address, args.pincode)
  File "/home/frank/Downloads/defogger-master/./dcs8000lh-configure.py", line 28, in __init__
    self.periph = Peripheral(address)
  File "/usr/local/lib/python3.10/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.10/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral b0:c5:54:4c:2d:80, addr type: public

**Comment by phk-r** [comment]
This is exactly the same error I get when trying to connect to my DCS-8525LH. 
Scanning with "hcitool" doesnt even find the camera, at least not with the same MAC as on the label.
Its like BT isnt enable on the camera, but that doesnt sound very likely.

I might add that I have connected the camera to my network and the firmware seems to be 1.07.03(3.5.22-b01).
Also did a scan with nmap:

```
PORT     STATE SERVICE
8080/tcp open  http-proxy
8081/tcp open  blackice-icecap
8088/tcp open  radan-http
```

Will try to continue my research to see if I missed something or can change firmware somehow to better match what @bmork was using.

**Comment by aguaviva** [comment]
> DCS-8525LH

@phk-r I have this camera too, could you please share your firmware so I can try too in parallel? (This model has been discontinued in Europe and I cannot use the app anymore)

**Comment by phk-r** [comment]
> > DCS-8525LH
> 
> @phk-r I have this camera too, could you please share your firmware so I can try too in parallel? (This model has been discontinued in Europe and I cannot use the app anymore)

My cameras have firmware 1.07.03(3.5.22-b01).
And as of now I dont use them at all. Without RTSP or other way to use them with Frigate, they are of no use to me.
