### ISSUE TITLE
Serial Console outputting gibberish

### ISSUE THREAD

**Issue by OmegaLeWolf** [bmork/defogger#36]
I'm currently attempting this on a P6000LH which by all means should work from what I researched.
The camera is currently on firmware version 1.06.01

I've been following along with mostly no issues, though once I got the serial connected it outputs gibberish. I've used multiple different Baud values and messed with the parity to no change. 

Does anyone have any suggestions?

(Image of my setup, using a Serial Cisco cable)
https://imgur.com/a/twDbGlH

**Comment by bmork** [comment]
> Image of my setup, using a Serial Cisco cable)
> https://imgur.com/a/twDbGlH

This won't work. You are connecting RS232 with possibly 12V levels to 3.3V input.

You need a "TTL" dongle or something else using 3.3V, like a RPi

**Comment by OmegaLeWolf** [comment]
I see I see. Thank you lots! I'll give this a go and update.

**Comment by OmegaLeWolf** [comment]
Worked! Thank ya.
