### ISSUE TITLE
Motion trigger

### ISSUE THREAD

**Issue by OneBobone** [bmork/defogger#6]
Hi!
Would anyone know how to capture a motion triggered event?
As set in the app/web interface.
Cheers,
Bob

**Comment by bmork** [comment]
Not sure exactly what you mean... Did you try the motion.cgi and notify.cgi endpoints documented in http://gurau-audibert.hd.free.fr/josdblog/wp-content/uploads/2013/09/CGI_2121.pdf ?

FWIW I prefer use these cameras in streaming mode and do the motion detection on another server running "motion". So I don't have much experience with the built-in motion detection.
