### ISSUE TITLE
Works for firmware v2.01.03

### ISSUE THREAD

**Issue by PushkarChatterji** [bmork/defogger#7]
Hi, Thanks for such awesome work. 

I can confirm that the entire process works flawlessly for firmware v2.01.03.

Off topic: 
How does one turn off the 'motion detect' mode? The cam keeps disconnecting when it fails to detect motion after a few seconds. 

The code I am using in python is:

import cv2

cap = cv2.VideoCapture("rtsp://admin:xxxxxxx@192.168.1.106/live/profile.0")

# Check if the webcam is opened correctly
if not cap.isOpened():
    raise IOError("Cannot open webcam")

while True:
	ret, frame = cap.read()
    	cv2.imshow('Input', frame)
	cap.release()
	
	c = cv2.waitKey(1)
	if c == 27:
		break

cap.release()
cv2.destroyAllWindows()

**Comment by bmork** [comment]
PushkarChatterji <notifications@github.com> writes:

> I can confirm that the entire process works flawlessly for firmware v2.01.03.

great!


> Off topic: 
> How does one turn off the 'motion detect' mode? The cam keeps disconnecting when it fails to detect motion after a few seconds. 

Not sure. Haven't really seen any such issues.  I have this:

 bjorn@canardo:~$ curl -u admin:xxxxxxx http://192.168.22.33/config/motion.cgi
 enable=yes
 mbmask=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
 sensitivity=90
 pir_sensitivity=10


So maybe

 curl -u admin:xxxxxxx http://192.168.22.33/config/motion.cgi?enable=no

will do?


Bjørn

**Comment by PushkarChatterji** [comment]
So maybe curl -u admin:xxxxxxx http://192.168.22.33/config/motion.cgi?enable=no will do? Bjørn

Yep! That works. Thanks!
