### ISSUE TITLE
Disabling text overlay

### ISSUE THREAD

**Issue by PushkarChatterji** [bmork/defogger#8]
My camera has a text overlay with the Date_Time stamp and the Model name in the feed that i access via rtsp. 

Is there any way to disable this overlay? 

I tried looking up the NICA API list but couldn't find a solution.

**Comment by bmork** [comment]
PushkarChatterji <notifications@github.com> writes:

> My camera has a text overlay with the Date_Time stamp and the Model name in the feed that i access via rtsp. 
>
> Is there any way to disable this overlay? 
>
> I tried looking up the NICA API list but couldn't find a solution.

You can switch of the OSD using

 curl -u admin:<pincode> http://<ipadress>/config/timestamp.cgi?enable=off

No, "timestamp" isn't a very obvious keyword here...


Bjørn

**Comment by PushkarChatterji** [comment]
Thank you! That worked just fine!
